# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa20c11adfdcf32f5138976e3232f249823c21a12969fefc79b3e9e02c5c4a4aef73ad96a88a0d1d34d7079b8c79af04d54829cf149c5a610e0f0b3169a8ea8a

test:
  secret_key_base: 83ab14c0928438d2c5facee4b22cd46b4c5c1aae5ca353f7297205748cf5ed312b10f2f54d9b8eea4f700ad57bad7b2e212bb8b53c756db62ff5a3c1ccb52e35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
